baseurl = ""
title = "Food4Thought"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true

publishDir = "docs"

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  header_image = "img/Food4Thought_home.jpg"
  SEOTitle = "Rola Dali's Blog"
  description = "Journals of a meandering mind: topics/tutorials in Computer Science, Data Science, Bioinformatics, The Sciences, and Society..."
  keyword = "Rola Dali, Tutorials, genomics, computer Science, Data Science, Bioinformatics, R, python"
  slogan = "Work Smarter; Not Harder..."

  image_404 = "img/404-bg.jpg"
  title_404 = "Ooops! This page is not here :("

  # leancloud storage for page view counter
  page_view_conter = false
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = false 
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Sidebar settings
  sidebar_about_description = "Software Developer, Data Analyst and a wonderer"
  sidebar_avatar = "img/RolaDali.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true 
  featured_condition_size = 2 

  # Baidu Analytics
  ba_track_id = ""
  
  # We need a proxy to access Disqus api in China
  disqus_proxy = ""
  disqus_site = ""

  [params.social]
  rss            = true 
  email          = "roladali@gmail.com"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  twitter       = "https://twitter.com/rdali094"
  linkedin       = "https://www.linkedin.com/in/rola-dali-phd-63b7133a/"
  #stackoverflow  = "full profile url in stackoverflow"
  #instagram     = "full profile url in instagram"
  github         = "https://github.com/rdali"
  #wechat         = "link of wechat QR code image"
  #pinterest     = "full profile url in pinterest"
  
  #[[params.friend_link]]
  #title = "Jean"
  #href =  "https://zhaozhihan.com"

#  [[params.bookmark_link]]
#  title =  "Martin Fowler"
#  href =  "https://martinfowler.com"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"]
